services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: lab-mqtt
    restart: unless-stopped
    user: "1883:1883"
    networks:
      - iot-frontend
    volumes:
      - ${PATH_MQTT_DATA}:/mosquitto/data:rw
      # Hardening: La config se lee, no se toca desde el contenedor
      - ./mosquitto/config:/mosquitto/config:ro 

  influxdb:
    image: influxdb:1.8
    container_name: lab-influx
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - iot-backend
    volumes:
      - ${PATH_INFLUX_DATA}:/var/lib/influxdb:rw

  node-red:
    image: nodered/node-red:latest
    container_name: lab-nodered
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    environment:
      - TZ=Europe/Madrid
    networks:
      - iot-frontend
      - iot-backend
    volumes:
      - ${PATH_NODERED_DATA}:/data:rw
    depends_on:
      - mosquitto
      - influxdb

networks:
  iot-frontend:
    driver: bridge
  iot-backend:
    internal: true # Capa de seguridad: red aislada de internet