services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: lab-mqtt
    restart: unless-stopped
    user: "1883:1883"
    ports:
      - "1883:1883"
    networks:
      - iot-frontend
    volumes:
      - ${PATH_MQTT_DATA}:/mosquitto/data:rw
      - ./mosquitto/config:/mosquitto/config:ro

  influxdb:
    image: influxdb:1.8
    container_name: lab-influx
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    # InfluxDB no necesita puertos hacia afuera ni red frontend
    networks:
      - iot-backend
    volumes:
      - ${PATH_INFLUX_DATA}:/var/lib/influxdb:rw

  node-red:
    image: nodered/node-red:latest
    container_name: lab-nodered
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    networks:
      - iot-frontend # Para escuchar a Mosquitto
      - iot-backend  # Para escribir en InfluxDB
    volumes:
      - ${PATH_NODERED_DATA}:/data:rw
    depends_on:
      - mosquitto
      - influxdb

  grafana:
    image: grafana/grafana-oss:latest
    container_name: lab-grafana
    restart: unless-stopped
    user: "472"
    ports:
      - "3000:3000"
    networks:
      - iot-frontend # Para que tú accedas vía web/Cloudflare
      - iot-backend  # Para leer los datos de InfluxDB
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

networks:
  iot-frontend:
    driver: bridge
  iot-backend:
    internal: true # Aislamiento total de internet y de la red externa