persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
listener 1883
allow_anonymous true

#El día de mañana, si quieres blindar tu Mosquitto al 100%, solo tendrás que cambiar a allow_anonymous false y añadir la ruta a un archivo de contraseñas (password_file) generado con la herramienta mosquitto_passwd